-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 15:03:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JETSKATESHOP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JETSKATESHOP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JETSKATESHOP` DEFAULT CHARACTER SET utf8 ;
USE `JETSKATESHOP` ;

-- -----------------------------------------------------
-- Table `JETSKATESHOP`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JETSKATESHOP`.`user` ;

CREATE TABLE IF NOT EXISTS `JETSKATESHOP`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `e-mail` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `cellphone` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JETSKATESHOP`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JETSKATESHOP`.`adress` ;

CREATE TABLE IF NOT EXISTS `JETSKATESHOP`.`adress` (
  `idadress` INT NOT NULL,
  `rua` VARCHAR(100) NULL,
  `numero` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idadress`),
  CONSTRAINT `adress_id`
    FOREIGN KEY ()
    REFERENCES `JETSKATESHOP`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JETSKATESHOP`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JETSKATESHOP`.`order` ;

CREATE TABLE IF NOT EXISTS `JETSKATESHOP`.`order` (
  `idorder` INT NOT NULL,
  `number` VARCHAR(45) NULL,
  `qtde` DECIMAL(45) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `JETSKATESHOP`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JETSKATESHOP`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JETSKATESHOP`.`products` ;

CREATE TABLE IF NOT EXISTS `JETSKATESHOP`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  `cor` VARCHAR(45) NULL,
  `tamanho` DECIMAL(10) NULL,
  `price` DECIMAL(10) NULL,
  `discount` DECIMAL(10) NULL,
  `productscol` VARCHAR(45) NULL,
  `order_idorder` INT NOT NULL,
  PRIMARY KEY (`idproducts`),
  INDEX `fk_products_order1_idx` (`order_idorder` ASC) VISIBLE,
  CONSTRAINT `fk_products_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `JETSKATESHOP`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JETSKATESHOP`.`type_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JETSKATESHOP`.`type_products` ;

CREATE TABLE IF NOT EXISTS `JETSKATESHOP`.`type_products` (
  `idtype_products` INT NOT NULL,
  `tenis` VARCHAR(45) NULL,
  `roupas` VARCHAR(45) NULL,
  `skate` VARCHAR(45) NULL,
  PRIMARY KEY (`idtype_products`),
  CONSTRAINT `type_products`
    FOREIGN KEY ()
    REFERENCES `JETSKATESHOP`.`products` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
